export const data=[
    {
        id:1,
        name:'Kadhakali',
        image:'kathakali.jpg',
        img:"kathakali.jpg",
        desc:'Kathakali is a major form of classical Indian dance.It is a story play genre of art, but one distinguished by the elaborately colourful make-up and costumes of the traditional male actor-dancers.',
        detail:"Kathakali is a major form of classical Indian dance.It is a story play genre of art, but one distinguished by the elaborately colourful make-up and costumes of the traditional male actor-dancers.It is native to the Malayalam-speaking southwestern region of Kerala and is almost entirely practiced and appreciated by Malayali people. Kathakali is one of the eight classical dances of India Hanuman in Kathakali (FACT Jayadeva Varma) Kathakali's roots are unclear. The fully developed style of Kathakali originated around the 17th century, but its roots are in the temple and folk arts (such as Krishnanattam and religious drama of the kingdom of the Zamorin of Calicut) southwestern Indian peninsula), which are traceable to at least the 1st millennium CE.A Kathakali performance, like all classical dance arts of India, synthesizes music, vocal performers, choreography and hand and facial gestures together to express ideas. However, Kathakali differs in that it also incorporates movements from ancient Indian martial arts and athletic traditions of South India.Kathakali also differs in that the structure and details of its art form developed in the courts and theatres of Hindu principalities, unlike other classical Indian dances which primarily developed in Hindu temples and monastic schools. The traditional themes of the Kathakali are folk stories, religious legends and spiritual ideas from the Hindu epics and the Puranas. The vocal performance has traditionally been performed in Sanskritised Malayalam. In modern compositions, Indian Kathakali troupes have included women artistes,and adapted Western stories and plays such as those by Shakespeare."
    },
    {
        id:2,
        name:'Theyyam',
        image:'theyyam1.jpg',
        img:"theyyam1.jpg",
        desc:'Theyyam are Hindu ritualistic dance forms practiced in northern Kerala and some parts of Karnataka. Theyyam consists of traditions, rituals and customs associated with the temples.',
        detail:"Theyyam are Hindu ritualistic dance forms practiced in northern Kerala and some parts of Karnataka.Theyyam consists of traditions, rituals and customs associated with temples.The people of the region consider Theyyam itself as a channel to a god and they thus seek blessings from Theyyam. In Kasaragod and Kannur districts, this ritual art is mainly performed in the kavus (temples) or ancestral houses of Nambiar, Thiyyar, Vaniyar and Maniyani communities.There are about 456 types of Theyyams documented. Theyyam is mainly performed by males, except the Devakoothu theyyam; the Devakoothu is the only Theyyam ritual performed by women.Devakoothu is performed only in the Thekkumbad Kulom temple. In Kerala, Theyyam is performed predominantly in the North Malabar region (consisting of present-day Kasargod, Kannur Districts, Mananthavady Taluk of Wayanad and Vadakara and Koyilandy Taluks of Kozhikode). A similar custom is followed in the Tulunadu region of neighbouring Karnataka known as Bhuta Kola. Theyyam season starts from the tenth day of the Malayalam month of Thulam (usually falls during October, and known as paththaam-udayam) and lasts up to seven months till the middle of Edavam month (typically around May end, June). The last Kaliyaattam for the season is performed at Madayi Kavu and Kalarivathukkal Bhagavathy Temple, Both being the family shrines of Kolathiri royal family."
    },
    {
        id:3,
        name:'Mohiniyattam',
        image:'mohiniyattam.jpg',
        img:"mohiniyattam.jpg",
        desc:'Mohiniyattam is an Indian classical dance form that developed in the state of Kerala.It follows the Lasya style described in Natya Shastra,a dance which is delicate,eros-filled and feminine',
        detail:"Mohiniyattam is an Indian classical dance form that developed in the state of Kerala.It follows the Lasya style described in Natya Shastra,a dance which is delicate,eros-filled and feminine powers.Mohiniyattam's roots, like all classical Indian dances, are in the Natya Shastra – the ancient Hindu Sanskrit text on performance arts. However, it follows the Lasya style described in Natya Shastra, that is a dance which is delicate, eros-filled and feminine. It is traditionally a solo dance performed by women after extensive training, though nowadays men can also perform the dance. The repertoire of Mohiniyattam includes music in the Carnatic style, singing and acting a play through the dance, where the recitation may be either by a separate vocalist or the dancer themselves. The song is typically in Malayalam-Sanskrit hybrid called Manipravalam. The earliest mention of the word is found in the 16th-century legal text Vyavaharamala, but the likely roots of the dance are older. The dance was systematized in the 18th century, was ridiculed as a Devadasi prostitution system during the colonial British Raj, banned by a series of laws from 1931 through 1938, a ban that was protested and partially repealed in 1940.The socio-political conflict ultimately led to renewed interest, revival and reconstruction of Mohiniyattam by the people of Kerala, particularly the poet Vallathol Narayana Menon. The costume includes plain white or off-white such as ivory or cream colored sari embroidered with bright golden or gold laced colored brocade (similar to a ceremonial Kasavu saree).She wears a fitted choli (blouse) matching the sari, below which at the waist is a golden belt which tucks in the end of the sari, and highlights the waist. In front of the saree, below the belt is pleated sheet with concentric bands in gold or saffron colors, which allow freedom of movement and assist in visually communicating the mudra to distant audience. The dancer wears relatively simple jewelry and no masks, in contrast to the other major classical dance of Kerala called Kathakali. Her jewelry typically includes items on fingers, wrists, neck and ears (which may have bells). The face makeup is natural, but lips are brilliant red, she has the Hindu tikka (Gobi) on her forehead and her eyes are lined to help prominently highlight the eye movements during the dance. Her ankles are adorned with leather straps with bells (chilanka), feet and fingers colored red with natural dyes. Her hairdo is gathered and tied into a smooth tight round chignon on one side of her head (typically left) and the bun then ringed with fragrant flowers (typically jasmine mulla)"
    },
    {
        id:4,
        name:'Kalaripayattu',
        image:'kalaripayattu.jpg',
        img:"kalaripayattu.jpg",
        desc:'Kalaripayattu is an Indian martial art that originated in modern-day Kerala.It is known for its long-standing history within Indian martial arts,and is one of the oldest surviving martial arts in India.',
        detail:"Kalaripayattu is an Indian martial art that originated in modern-day Kerala.It is known for its long-standing history within Indian martial arts,and is one of the oldest surviving martial arts in India.Kalaripayattu is mentioned in the Vadakkan Pattukal, a collection of ballads written about the Chekavar of the Malabar region of Kerala. In the Vadakkan Pattukal, it is stated that the cardinal principle of Kalaripayattu was that knowledge of the art be used to further worthy causes, and not for the advancement of one's own selfish interests.[10] Kalaripayattu is a martial art designed for the ancient battlefield (the word 'Kalari' meaning battlefield), with weapons and combative techniques that are unique to Kerala. Like most Indian martial arts, Kalaripayattu contains rituals and philosophies inspired by Hinduism.The art also bases medical treatments upon concepts found in the ancient Indian medical text, the Ayurveda. Practitioners of Kalaripayattu possess intricate knowledge of pressure points on the human body and healing techniques that incorporate the knowledge of Ayurveda and Yoga.Kalaripayattu is taught in accordance with the Indian guru-shishya system. Kalaripayattu differs from many other martial arts systems in the world in that weapon based techniques are taught first, and barehanded techniques are taught last. Elements from the yoga tradition as well as finger movements in the nata dances, were incorporated into Kalaripayattu. A number of South Asian fighting styles remain closely connected to yoga, dance and performing arts. Some of the choreographed sparring in Kalaripayattu can be applied to dance and Kathakali dancers who knew Kalaripayattu were believed to be markedly better than other performers. Some traditional Indian classical dance schools still incorporate martial arts as part of their exercise regimen."
    },
    {
        id:5,
        name:'Ottamthullal',
        image:'ottamthullal.jpg',
        img:"ottamthullal.jpg",
        desc:'Ottamthullal is a recite-and-dance art-form of Kerala.The folksy performance,often laced with humour intended at criticism of society,is accompanied by a mridangam and/or the handy idakka besides a pair of cymbals.',
        detail:"Ottamthullal is a recite-and-dance art-form of Kerala.The folksy performance,often laced with humour intended at criticism of society,is accompanied by a mridangam and/or the handy idakka besides a pair of cymbals.In Ottamthullal, a solo performer, with green makeup and a colourful costume (decorated with a long red and white band and painted wooden ornaments), acts and dances while reciting dance (Thullal) (lyrics).[4] A chorus or one or more artists repeats each sentence as it is completed. More recently, Ottamthullal has been performed with a solo female actor and with an ensemble cast. Nambiar parodies the ways of landlords and other prominent citizens, sometimes even the king. For example, the character of Bhima from the epic the Mahabharata is portrayed as an oaf. Higher castes including Brahmin are not spared.Ottan thullal is performed in Malayalam, which pleases local audiences. Old sayings and elements of folklore are used.There may be 64 or more Ottamthullal works. Examples include: Kallyana Sougandhikam (a rare flower), Bhima is searching for the flower and has a long conversation with his older brother, Hanuman. Kiratham, Garudagarva bhangam, Santhanagopalam, Ghoshayathra etc."
    },
    {
        id:6,
        name:'Padayani',
        image:'padayani.jpg',
        img:"padayani.jpg",
        desc:'Padayani is a traditional folk dance and a ritual art from the central portion of the Indian state of Kerala.A ceremonial dance involving masks,it is an ancient ritual performed in Bhagavati temples.',
        detail:"Padayani is a traditional folk dance and a ritual art from the central portion of the Indian state of Kerala.A ceremonial dance involving masks,it is an ancient ritual performed in Bhagavati temples. The dance is performed in honor of Bhadrakaali. Meaning, a 'row of warriors', Padayani is an art form that blends all music, dance, theatre, satire, facial masks, and paintings. It is part of worship of Bhadrakali and is staged in temples dedicated to the goddess from mid-December to mid-May. Padayani is unique to central Travancore, comprising the Pathanamthitta and kottayam districts of Kerala. Padayani is regarded as a remnant of the Dravidian forms of worship that existed before the advent of Brahmanism. Padayani is like Theyyam in north Kerala. The percussion instruments used in Patayani are patayani thappu, chenda, para and kumbham. Padayani at Puthukulangara Devi Temple, Othera, Pathanamthitta District is also famous. Here Bhairavi kolam which is on last day of festival is very famous. For making that 1001 bark of arecanut palm tree is used. Main festival is on star ThiruvathiraMeenamme month of Meena. 'Pachathapp' is the first Malayalam film based on Padayani. Pachathappu is written and directed by Anu Purushoth.Nominated, Kerala Film Critics Award for Best Art Film of 2020"
    },
    {
        id:7,
        name:'Kalamezhuthu',
        image:'kalamezhuthu.jpg',
        img:"kalamezhuthu.jpg",
        desc:'Kalamezhuthu is an ancient art woven into the ritualistic mores of Bhagavati,Naga and Ayyappa temples in Kerala.It refers to pictorial representation of deities on floor using coloured powders.',
        detail:"Kalamezhuthu is an ancient art woven into the ritualistic mores of Bhagavati,Naga and Ayyappa temples in Kerala.It refers to pictorial representation of deities on floor using coloured powders.When combined with the singing of specific songs (kalampaattu) and dance movements related to the puja (kalapradakshinam), it becomes a ritualistic performance known as ‘kalamezhuthum paattum’ or ‘kalamezhuthupaattu’.Maestros combine coloured powders to draw beautiful drawings on the floor, exalting and worshipping the great Gods of the land including Bhadrakaali, Ayyappan, Serpent or Vettakkorumakan. From temples to noble households, one sees these unique portraits accompanied by the Kalamezhuthupattu. These are erased at the end of the ritual, with the rhythms of various musical instruments like the ilathalam, veekkanchenda, kuzhal, kombu and chenda, acting as accompaniment. Only natural products are used for the ritual to make the Kalam, also called the dholichithram or powder drawing. The pigments are extracted from plants- rice flour (white), charcoal powder (black), turmeric powder (yellow), powdered green leaves (green), and a mixture of turmeric powder and lime (red). The entire process can take up to 2 hours and it is sometimes even decorated with a canopy of palm fronds, garlands of red hibiscus flowers and thulasi or Ocimum leaves. The artists have traditionally belonged to the Kurups, Theyyampadi Nambiars, Theeyadi Nambiars and Theeyadi Unnis communities, each having their own unique kalam traits. A wide range of emotions are expressed in these works, as the artists bare their very soul during the same."
    },
    {
        id:8,
        name:'Poorakkali',
        image:'poorakali.jpg',
        img:"poorakali.jpg",
        desc:'Poorakkali (meaning Festival Performance) is a traditional dance ritual performed by men during the nine-day Pooram festival in Bhagavathy temples across North Malabar in the Kerala State of south India.',
        detail:"Poorakkali (meaning Festival Performance) is a traditional dance ritual performed by men during the nine-day Pooram festival in Bhagavathy temples across North Malabar in Kerala State of south India.The Pooram festival begins with the Karthika asterism and concludes with the Pooram asterism of the month of Meenam according to the Malayalam calendar (corresponding to the sun sign Pisces according to the Julian Calendar) to honour Kamadeva, the god of love. The performers mainly come from Thiyya, Maniyani Different sects of society like also perform Poorakkali. The basis of Poorakkali essentially is the memories of Vasanthapooja performed by inmates of different worlds like heaven, earth etc. Poorakkali spreads knowledge and entertainment. The show steals the hearts of audience with melodious songs and befitting body movements. The Panickers are well-known names in the world of Poorakkali and have contributed much to the survival and expansion of this art form. The Poorakkali dance itself is performed by a troop of young men decked in lion costumes around a huge, multi-tiered, lit lamp, also known as a nilavilukku. The dance involves masculine movements and acrobatic, martial art steps. No singers or musicians accompany the dance; instead, the dancers themselves keep rhythm by singing, clapping and executing synchronised foot-thumping movements. The dancers usually observe a month of abstinence and undergo strenuous practice before the performance. Most of the songs sung are hymns from Ramayana, Mahabharata or Bhagavata. The leader of the group, known by the name Panicker, sings the song, and the lines are repeated in chorus by the other dancers. Certain rituals are performed before the dance starts.Marathukali is a variant of Poorakkali. This is a form performed by two parties competently. The ordinary play lacks the competent mood displayed in Marathukali. Big disputes ensue between two parties while performance is on and learned people dissuade both parties from further confrontation."
    },
    {
        id:9,
        name:'Madhubani Paintings',
        image:'madhubani.jpg',
        img:"madhubani.jpg",
        desc:'Madhubani painting was traditionally created by the women of various communities in the Mithila region of India.It originated from the Madhubani district of the Mithila region of Bihar.',
        detail:"Madhubani painting was traditionally created by the women of various communities in the Mithila region of India.It originated from Madhubani district of the Mithila region of Bihar.Madhubani is also a major export center of these paintings. This painting as a form of wall art was practiced widely throughout the region; the more recent development of painting on paper and canvas mainly originated among the villages around Madhubani, and it is these latter developments that led to the term Madhubani art being used alongside Mithila Painting. The paintings were traditionally done on freshly plastered mud walls and floors of huts, but now they are also done on cloth, handmade paper and canvas.Madhubani paintings are made from the paste of powdered rice. Madhubani painting has remained confined to a compact geographical area and the skills have been passed on through centuries, the content and the style have largely remained the same. Thus, Madhubani painting has received GI (Geographical Indication) status. Madhubani paintings use two-dimensional imagery, and the colors used are derived from plants. Ochre, Lampblack and Red are used for reddish-brown and black, respectively. Mithila paintings mostly depict people and their association with nature and scenes and deities from the ancient epics. Natural objects like the sun, the moon, and religious plants like tulsi are also widely painted, along with scenes from the royal court and social events like weddings. In this paintings generally, no space is left empty; the gaps are filled by paintings of flowers, animals, birds, and even geometric designs.Traditionally, painting was one of the skills that was passed down from generation to generation in the families of the Mithila Region, mainly by women .It is still practiced and kept alive in institutions spread across the Mithila region. Asha Jha of Madhubanipaints in Darbhanga,Vaidehi in Madhubani, Benipatti in Madhubani district and Gram Vikas Parishad in Ranti are some of the major centres of Madhubani painting which have kept this ancient art form alive"
    },
    {
        id:10,
        name:'Chakyar Koothu',
        image:'chakyarkoothu.jpg',
        img:"chakyarkoothu.jpg",
        desc:'Chakyar Koothu is a performance art from Kerala.It is primarily a type of highly refined monologue where the performer narrates episodes from Hindu epics and stories from the Puranas.',
        detail:"Chakyar Koothu is a performance art from Kerala.It is primarily a type of highly refined monologue where the performer narrates episodes from Hindu epics and stories from the Puranas.Sometimes, however, it is also a traditional equivalent of the modern stand-up comedy act, incorporating commentary on current socio-political events (and personal comments directed at the members of the audience).Koothu means dance ... which is a misnomer, as facial expressions are emphasized and there is minimal choreography. It is performed in the Koothambalam; a place inside Hindu temples specifically designed for performing Kutiyattam and Chakyar Koothu. Ideally, the performance takes place in conjunction with festivals, presented by members of the Chakyar community along with the Ambalavasi Nambiars. It is a solo performance, by a narrator in a distinctive headgear and black moustache with his torso smeared with sandalwood paste and red dots all over the body. The headgear resembles snake’s hood, to symbolise the narration by Anantha, the thousand headed serpent. The Chakyar narrates the story based on the Sanskrit style of 'Champu Prabandha'- a mixture of prose (gadya) and poetry (shloka). He begins with a prayer to the deity of the temple. He then goes on to narrate a verse in Sanskrit before explaining it in Malayalam. The narration uses wit and humor to draw parallels with current events and local situations. Koothu has traditionally been performed only by the Chakyar community. Two instruments accompany the performance - a mizhavu and a pair of ilathalam. This is different from the Nangiar Koothu, which is performed by women called Nangyarammas who belong to the Nambiar caste, and is a more highly refined theatre art."
    },
]